Ch1: ch1_template1.cpp ch1_item4_ABEntry1.cpp ch1_item4_ABEntry2.cpp
	g++ -std=c++11 ch1_template1.cpp -o Ch1_Template.out
	g++ -std=c++11 ch1_item4_ABEntry1.cpp -o Ch1_item3_ABEntry1.out
	g++ -std=c++11 ch1_item4_ABEntry2.cpp -o Ch1_item3_ABEntry2.out
