Ch2: ch2_item5_NamedObj.cpp ch2_item6_Prevent.cpp ch2_item7_Virtual.cpp TimeKeeper.h
	g++ -std=c++11 ch2_item5_NamedObj.cpp -o Ch2_item5_NamedObj.out
#	g++ -std=c++11 ch2_item6_Prevent.cpp -o Ch2_item6_Prevent.out
	g++ -std=c++11 ch2_item7_Virtual.cpp -o Ch2_item7_Virtual.out
