Ch2: ch2_item5_NamedObj.cpp #item4_ABEntry2.cpp
	g++ -std=c++11 ch2_item5_NamedObj.cpp -o Ch2_item5_NamedObj.out
	#g++ -std=c++11 ch1_item4_ABEntry1.cpp -o Ch1_item3_ABEntry1.out
	#g++ -std=c++11 ch1_item4_ABEntry2.cpp -o Ch1_item3_ABEntry2.out
