Ch2: ch2_item5_NamedObj.cpp ch2_item6_Prevent.cpp
	g++ -std=c++11 ch2_item5_NamedObj.cpp -o Ch2_item5_NamedObj.out
	g++ -std=c++11 ch2_item6_Prevent.cpp -o Ch2_item6_Prevent.out
	#g++ -std=c++11 ch1_item4_ABEntry2.cpp -o Ch1_item3_ABEntry2.out
